services:
  traefik-route-control:
    build: .
    image: traefik-route-control
    container_name: traefik-route-control
    # Mount the .env file from the host to the container
    volumes:
      - ./data:/app/data
    # Expose the port for the API server
    ports:
      - "5000:5000"
    # Use host networking so the script can access a local Redis instance easily.
    # If Redis is on a different server, you can remove this line.
    #network_mode: host
    # Default command to run the API server
