services:
  routeghost:
    build:
      context: .
      args:
        - PUID=1000
        - PGID=1000
    image: routeghost
    container_name: routeghost
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    cap_add:
      - NET_ADMIN
    # Mount the data volume
    volumes:
      - routeghost_data:/app/data
    # Expose the port for the API server
    ports:
      - "5000:5000"
    # Use host networking so the script can access a local Redis instance easily.
    # If Redis is on a different server, you can remove this line.
    #network_mode: host
    # Default command to run the API server

volumes:
  routeghost_data:
