services:
  traefik-route-control:
    image: ghcr.io/m1ckyb/traefik-route-control:0.0.11
    # Volume for persistent database storage
    volumes:
      - ./data:/app/data
    # Expose the port for the web UI and API
    ports:
      - "5000:5000"
    # Use host networking so the script can access a local Redis instance easily.
    # If Redis is on a different server, you can remove this line.
    pull_policy: always
    restart: unless-stopped
