services:
  routeghost:
    image: ghcr.io/m1ckyb/routeghost:0.0.20
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    # Volume for persistent database storage
    volumes:
      - routeghost_data:/app/data
    # Expose the port for the web UI and API
    ports:
      - "5000:5000"
    # Use host networking so the script can access a local Redis instance easily.
    # If Redis is on a different server, you can remove this line.
    pull_policy: always
    restart: unless-stopped

volumes:
  routeghost_data:
